# Generated by Django 5.1.6 on 2025-04-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='In Transit', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.campaign')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.destination')),
            ],
        ),
        migrations.CreateModel(
            name='ContentInParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.content')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.parcel')),
            ],
        ),
    ]
